custom_function: demo.complete_task.complete_task
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 10000
      diversify: false
      expected_param_name: ""
      input_function:
        description:
          This function creates a concise and engaging TikTok video title.
          It uses the provided content summary and target audience to generate a title
          that is relevant and appealing to the specified demographic. The function
          takes into consideration the interests and preferences of the target audience
          to ensure the title is attractive and encourages viewership.
        name: generate_tiktok_video_title_based_on_content_and_audience
        parameters:
          target_audience: str
      model_name: gpt-4
      number_of_examples: 5
      output_csv_path: generate_tiktok_video_title_based_on_content_and_audience_generated_data.csv
      output_path: generate_tiktok_video_title_based_on_content_and_audience_generated_data.pkl
      prompt:
        "\n        \"Please provide a concrete and realistic test case as a\
        \ dictionary for function invocation using the ** operator.\n        Only\
        \ include parameters, excluding description and name.\n        Ensure it's\
        \ succinct and well-structured.\n        **Only provide the dictionary.**\"\
        \    \n    "
      single_shot: true
  source_type: machine_generated
description:
  Auto generated config for generate a short tiktok video title based on
  the {{content summary}} and {{target_audience}}
enhancer:
  end_meta_instruction:
    Give me a new prompt that is different from all pairs above,
    and has evaluation values on accuracy, appeal, keyword usage, emoji, oneline,
    that are higher than any of above.
  enhance_var:
    - task
  head_meta_instruction:
    "Now you will help me generate a prompt which is used to
    generate a corresponding TikTok video title based on the content summary [content
    summary] and target audience [target audience]. I already have some prompt and
    its evaluation results:"
  max_iterations: 2
  model_name: gpt-4
  name: optimize_by_prompt_enhancer
evaluators:
  - choice_scores:
      A: 0
      B: 1
      C: 2
      D: 3
      E: 4
    choices:
      - A
      - B
      - C
      - D
      - E
    description:
      Does the title accurately reflect the content of the TikTok video?
      The title should give viewers a clear idea of what to expect from the video content.
    display_name: accuracy
    evaluator_type: individual
    metric_calculators:
      - method: AVERAGE
    model_name: gpt-4
    name: openai_prompt_based_evaluator
    prompt:
      "You are assessing a submitted answer on a given task based on a criterion.
      Here is the data:

      This function creates a concise and engaging TikTok video title. It uses the provided
      content summary and target audience to generate a title that is relevant and appealing
      to the specified demographic. The function takes into consideration the interests
      and preferences of the target audience to ensure the title is attractive and encourages
      viewership.

      Does the title accurately reflect the content of the TikTok video? The title should
      give viewers a clear idea of what to expect from the video content.

      [Input]: target_audience: {{target_audience}}

      [Result]: {raw_output}

      Answer the question by selecting one of the following options:

      A It fails to meet the criterion at all.

      B It somewhat meets the criterion, but there is significant room for improvement.

      C It meets the criterion to a satisfactory degree.

      D It meets the criterion very well.

      E It meets the criterion exceptionally well, with little to no room for improvement."
    scale_description: 0-4
  - choice_scores:
      A: 0
      B: 1
      C: 2
      D: 3
      E: 4
    choices:
      - A
      - B
      - C
      - D
      - E
    description:
      Is the title appealing and engaging to the target audience? The title
      should be crafted in a way that it attracts the attention of the specified demographic
      and encourages them to watch the video.
    display_name: appeal
    evaluator_type: individual
    metric_calculators:
      - method: AVERAGE
    model_name: gpt-4
    name: openai_prompt_based_evaluator
    prompt:
      "You are assessing a submitted answer on a given task based on a criterion.
      Here is the data:

      This function creates a concise and engaging TikTok video title. It uses the provided
      content summary and target audience to generate a title that is relevant and appealing
      to the specified demographic. The function takes into consideration the interests
      and preferences of the target audience to ensure the title is attractive and encourages
      viewership.

      Is the title appealing and engaging to the target audience? The title should be
      crafted in a way that it attracts the attention of the specified demographic and
      encourages them to watch the video.

      [Input]: target_audience: {{target_audience}}

      [Result]: {raw_output}

      Answer the question by selecting one of the following options:

      A It fails to meet the criterion at all.

      B It somewhat meets the criterion, but there is significant room for improvement.

      C It meets the criterion to a satisfactory degree.

      D It meets the criterion very well.

      E It meets the criterion exceptionally well, with little to no room for improvement."
    scale_description: 0-4
  - choice_scores:
      A: 0
      B: 1
      C: 2
      D: 3
      E: 4
    choices:
      - A
      - B
      - C
      - D
      - E
    description:
      Does the title incorporate trending or popular keywords relevant to
      the target audience? Using trending or popular keywords can increase the visibility
      of the video and attract more viewers from the target audience.
    display_name: keyword usage
    evaluator_type: individual
    metric_calculators:
      - method: AVERAGE
    model_name: gpt-4
    name: openai_prompt_based_evaluator
    prompt:
      "You are assessing a submitted answer on a given task based on a criterion.
      Here is the data:

      This function creates a concise and engaging TikTok video title. It uses the provided
      content summary and target audience to generate a title that is relevant and appealing
      to the specified demographic. The function takes into consideration the interests
      and preferences of the target audience to ensure the title is attractive and encourages
      viewership.

      Does the title incorporate trending or popular keywords relevant to the target
      audience? Using trending or popular keywords can increase the visibility of the
      video and attract more viewers from the target audience.

      [Input]: target_audience: {{target_audience}}

      [Result]: {raw_output}

      Answer the question by selecting one of the following options:

      A It fails to meet the criterion at all.

      B It somewhat meets the criterion, but there is significant room for improvement.

      C It meets the criterion to a satisfactory degree.

      D It meets the criterion very well.

      E It meets the criterion exceptionally well, with little to no room for improvement."
    scale_description: 0-4
  - choice_scores:
      A: 0
      B: 1
      C: 2
      D: 3
      E: 4
    choices:
      - A
      - B
      - C
      - D
      - E
    description:
      Does the emoji used in the title clearly represent the content summary
      and target audience? It should be immediately clear to anyone who sees the emoji
      what the TikTok video's content and target audience are.
    display_name: emoji
    evaluator_type: individual
    metric_calculators:
      - method: AVERAGE
    model_name: gpt-4
    name: openai_prompt_based_evaluator
    prompt:
      "You are assessing a submitted answer on a given task based on a criterion.
      Here is the data:

      This function creates a concise and engaging TikTok video title. It uses the provided
      content summary and target audience to generate a title that is relevant and appealing
      to the specified demographic. The function takes into consideration the interests
      and preferences of the target audience to ensure the title is attractive and encourages
      viewership.

      Does the emoji used in the title clearly represent the content summary and target
      audience? It should be immediately clear to anyone who sees the emoji what the
      TikTok video's content and target audience are.

      [Input]: target_audience: {{target_audience}}

      [Result]: {raw_output}

      Answer the question by selecting one of the following options:

      A It fails to meet the criterion at all.

      B It somewhat meets the criterion, but there is significant room for improvement.

      C It meets the criterion to a satisfactory degree.

      D It meets the criterion very well.

      E It meets the criterion exceptionally well, with little to no room for improvement."
    scale_description: 0-4
  - choice_scores:
      A: 0
      B: 1
      C: 2
      D: 3
      E: 4
    choices:
      - A
      - B
      - C
      - D
      - E
    description:
      Does the generated TikTok video title succinctly summarize the content
      and target audience in a single line? The title should be concise, catchy, and
      effectively encapsulate the essence of the content and its intended audience in
      one line.
    display_name: oneline
    evaluator_type: individual
    metric_calculators:
      - method: AVERAGE
    model_name: gpt-4
    name: openai_prompt_based_evaluator
    prompt:
      "You are assessing a submitted answer on a given task based on a criterion.
      Here is the data:

      This function creates a concise and engaging TikTok video title. It uses the provided
      content summary and target audience to generate a title that is relevant and appealing
      to the specified demographic. The function takes into consideration the interests
      and preferences of the target audience to ensure the title is attractive and encourages
      viewership.

      Does the generated TikTok video title succinctly summarize the content and target
      audience in a single line? The title should be concise, catchy, and effectively
      encapsulate the essence of the content and its intended audience in one line.

      [Input]: target_audience: {{target_audience}}

      [Result]: {raw_output}

      Answer the question by selecting one of the following options:

      A It fails to meet the criterion at all.

      B It somewhat meets the criterion, but there is significant room for improvement.

      C It meets the criterion to a satisfactory degree.

      D It meets the criterion very well.

      E It meets the criterion exceptionally well, with little to no room for improvement."
    scale_description: 0-4
human_rating_configs:
  - instructions:
      Does the title accurately reflect the content of the TikTok video?
      The title should give viewers a clear idea of what to expect from the video content.
    name: accuracy
    scale:
      - 0
      - 4
  - instructions:
      Is the title appealing and engaging to the target audience? The title
      should be crafted in a way that it attracts the attention of the specified demographic
      and encourages them to watch the video.
    name: appeal
    scale:
      - 0
      - 4
  - instructions:
      Does the title incorporate trending or popular keywords relevant to
      the target audience? Using trending or popular keywords can increase the visibility
      of the video and attract more viewers from the target audience.
    name: keyword usage
    scale:
      - 0
      - 4
  - instructions:
      Does the emoji used in the title clearly represent the content summary
      and target audience? It should be immediately clear to anyone who sees the emoji
      what the TikTok video's content and target audience are.
    name: emoji
    scale:
      - 0
      - 4
  - instructions:
      Does the generated TikTok video title succinctly summarize the content
      and target audience in a single line? The title should be concise, catchy, and
      effectively encapsulate the essence of the content and its intended audience in
      one line.
    name: oneline
    scale:
      - 0
      - 4
selection_strategy:
  ahp_selection:
    criteria:
      - "openai_prompt_based_evaluator: accuracy"
      - "openai_prompt_based_evaluator: appeal"
      - "openai_prompt_based_evaluator: keyword usage"
      - "openai_prompt_based_evaluator: emoji"
      - "openai_prompt_based_evaluator: oneline"
      - average_token_usage
      - average_latency
    criteria_maximization:
      average_latency: false
      average_token_usage: false
      "openai_prompt_based_evaluator: accuracy": true
      "openai_prompt_based_evaluator: appeal": true
      "openai_prompt_based_evaluator: emoji": true
      "openai_prompt_based_evaluator: keyword usage": true
      "openai_prompt_based_evaluator: oneline": true
    criteria_weights:
      average_latency: 0
      average_token_usage: 0
      "openai_prompt_based_evaluator: accuracy": 0.2
      "openai_prompt_based_evaluator: appeal": 0.2
      "openai_prompt_based_evaluator: emoji": 0.2
      "openai_prompt_based_evaluator: keyword usage": 0.2
      "openai_prompt_based_evaluator: oneline": 0.2
variations:
  - generator_config: null
    generator_name: null
    name: task
    variations:
      - instantiated_value:
          generate a short tiktok video title based on the {{content
          summary}} and {{target_audience}}
        value:
          generate a short tiktok video title based on the {{content summary}} and
          {{target_audience}}
        value_type: str
        variation_id: null
