custom_function: demo.building_design.building_design
description: Generated experiment config
dataset:
  data_generators:
    openai_prompt_data_generator:
      chunk_size: 1000
      diversify: true
      prompt:
          "Please provide a concrete and realistic test case as a dictionary for function invocation using the ** operator.
          Only include parameters, excluding description and name.
          Ensure it's succinct and well-structured.
          **Only provide the dictionary.**"
      input_function:
        description:
          Given the geographical location of the building and the actual function of the building, generate a description of the exterior scene of the building.
        name: building_design_generation
        parameters:
          location: str
          function: str
      number_of_examples: 1
      model_name: gpt-4
  source_type: machine_generated

variations:
  - name: task
    generator_name: openai_prompt_based_variation_generator
    generator_config:
      model_name: gpt-4
      number_of_variations: 1
      diversify: false
      max_tokens: 2000
      variables: null
      prompt: 
        - content: |-
                Your objective is to construct a concise instruction prompt for GPT-4. This prompt will instruct GPT-4 as an innovative, architectural designer to create diverse building design variations based on geographical location and building function.

                Points to emphasize in your instruction:
                  - GPT-4 responses should include a brief design concept and should be sufficiently imaginative. Responses should focus on the geographical location and the function of the building. The design can be contrary to common architectural norms, dream-like or realistic.
                  - The design description must be kept lively and as short, short, short, short, short as possible. The design should have a variety of features and fully emphasize the geographical location; it can be dreamlike and generally bizarre.
                  - Be sure to use words that are as easy to understand as possible so TEENAGERS can easily understand the design concept.
                  - Please limit the output to within 300 words
                  - {building_location} represents the geographical location of the building
                  - {building_function} represents the function of the building
                  - At all times, GPT-4 must give a response as a building design variation

                Craft your instruction. Ensure that GPT-4 is able to fully understand the geographical location and function of the building and create engaging and fully pictorial designs.
                Keep your output crisp: only the prompt, devoid of any extraneous content.

          role: system

evaluators:
  - evaluator_type: individual
    metric_calculators:
      - method: AVERAGE
    name: openai_prompt_based_evaluator
    display_name: description_quality
    prompt: |-
      You are assessing a submitted building design description based on a given task and criterion. Here is the data:
      - Task: Given the geographical location and function of a building, generate a design description.
      - Does the description demonstrate creativity, coherence, and engaging narrative? A well-written description should captivate the reader and effectively convey a compelling design concept with clear structure and functional development.
      [Input]: building_location : {location}, building_function: {function}
      [Result]: {raw_output}
      Answer the question by selecting one of the following options:
      A The description is of very low quality and lacks coherence and engagement.
      B The description has some issues with coherence and engagement, but has potential for enhancement.
      C The description is of satisfactory quality, but there is room for enhancement.
      D The description is well-written and demonstrates good coherence and engagement.
      E The description is exceptionally well-written, demonstrating strong coherence and engagement.
    choices: ["A", "B", "C", "D", "E"]
    model_name: gpt-4
    description: "evaluate the quality of the generated building design"
    scale_description: "0-4"
    choice_scores:
      A: 0
      B: 1
      C: 2
      D: 3
      E: 4



selection_strategy:
  ahp_selection:
    criteria:
      - "openai_prompt_based_evaluator: description_quality"
      - average_token_usage
      - average_latency
    criteria_maximization:
      "openai_prompt_based_evaluator: description_quality": true
      average_latency: false
      average_token_usage: false
    criteria_weights:
      "openai_prompt_based_evaluator: description_quality": 1
      average_latency: 0.0
      average_token_usage: 0.0
    normalize_func: "z-score"
