custom_function: demo.retriever_compare.retriever_compare
dataset:
  file_path: demo/data/retriever_compare.csv
  reader: csv_reader
  source_type: dataset
  reader_config:
    expected_result_column: expected_result
description: Configuration fo question answering with expected results.

variations:
  - name: retriever_name
    variations:
      - instantiated_value: "MultiQueryRetriever"
        value: "MultiQueryRetriever"
        value_type: str
        variation_id: null
      - instantiated_value: "Contextual_compression"
        value: "Contextual_compression"
        value_type: str
        variation_id: null
      - instantiated_value: "Ensemble_Retriever"
        value: "Ensemble_Retriever"
        value_type: str
        variation_id: null
      - instantiated_value: "MultiVector_Retriever"
        value: "MultiVector_Retriever"
        value_type: str
        variation_id: null
      - instantiated_value: "Parent_Document_Retriever"
        value: "Parent_Document_Retriever"
        value_type: str
        variation_id: null
      - instantiated_value: "llamaindex"
        value: "llamaindex"
        value_type: str
        variation_id: null


human_rating_configs:
  - name: answer_quility
    instructions: Please rate the quality of the answer provided by the model
    scale: [1, 5]

